/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanagementapp;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUSROG
 */
public class Admin extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        loadAdminTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblSystemImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnItem = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlJudul = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        lblAdminCode = new javax.swing.JLabel();
        txtAdminCode = new javax.swing.JTextField();
        lblSupplierCode1 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        lblAdminUsername = new javax.swing.JLabel();
        lblAdminPass = new javax.swing.JLabel();
        lblAdminEmail = new javax.swing.JLabel();
        lblAdminPhone = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        txtAdminPassword = new javax.swing.JTextField();
        txtAdminEmail = new javax.swing.JTextField();
        txtAdminPhone = new javax.swing.JTextField();
        btnAdminAdd = new javax.swing.JButton();
        btnAdminUpdate = new javax.swing.JButton();
        btnAdminDelete = new javax.swing.JButton();
        btnClearAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(88, 111, 124));

        pnlLeft.setBackground(new java.awt.Color(47, 69, 80));

        lblSystemImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-system.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 244, 249));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Management System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 249));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventory");

        btnItem.setBackground(new java.awt.Color(184, 219, 217));
        btnItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-item-32.png"))); // NOI18N
        btnItem.setText("     Item");
        btnItem.setBorder(null);
        btnItem.setFocusPainted(false);
        btnItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });

        btnCategory.setBackground(new java.awt.Color(184, 219, 217));
        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-category-32.png"))); // NOI18N
        btnCategory.setText("    Category");
        btnCategory.setBorder(null);
        btnCategory.setFocusPainted(false);
        btnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-warehouse-32.png"))); // NOI18N
        btnSupplier.setText("    Supplier");
        btnSupplier.setBorder(null);
        btnSupplier.setFocusPainted(false);
        btnSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(184, 219, 217));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-admin-32.png"))); // NOI18N
        btnAdmin.setText("   Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin.setIconTextGap(10);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        lblLogout.setForeground(new java.awt.Color(184, 219, 217));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-logout-32.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setPreferredSize(new java.awt.Dimension(30, 30));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblSystemImg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSystemImg)
                .addGap(27, 27, 27)
                .addComponent(btnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlRight.setBackground(new java.awt.Color(88, 111, 124));

        pnlJudul.setBackground(new java.awt.Color(88, 111, 124));

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(244, 244, 249));
        lblAdmin.setText("Admin");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-back-32.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlJudulLayout = new javax.swing.GroupLayout(pnlJudul);
        pnlJudul.setLayout(pnlJudulLayout);
        pnlJudulLayout.setHorizontalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlJudulLayout.setVerticalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addGroup(pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJudulLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblBack))
                    .addGroup(pnlJudulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pnlForm.setBackground(new java.awt.Color(88, 111, 124));

        lblAdminCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminCode.setForeground(new java.awt.Color(244, 244, 249));
        lblAdminCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdminCode.setText("Admin Code :");

        txtAdminCode.setEditable(false);
        txtAdminCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAdminCode.setEnabled(false);
        txtAdminCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminCodeActionPerformed(evt);
            }
        });
        txtAdminCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdminCodeKeyTyped(evt);
            }
        });

        lblSupplierCode1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierCode1.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierCode1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierCode1.setText("Admin Name :");

        txtAdminName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblAdminUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminUsername.setForeground(new java.awt.Color(244, 244, 249));
        lblAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdminUsername.setText("Username :");

        lblAdminPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminPass.setForeground(new java.awt.Color(244, 244, 249));
        lblAdminPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdminPass.setText("Password :");

        lblAdminEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminEmail.setForeground(new java.awt.Color(244, 244, 249));
        lblAdminEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdminEmail.setText("Email :");

        lblAdminPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminPhone.setForeground(new java.awt.Color(244, 244, 249));
        lblAdminPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdminPhone.setText("Phone Number :");

        txtAdminUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtAdminPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtAdminEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtAdminPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnAdminAdd.setBackground(new java.awt.Color(184, 219, 217));
        btnAdminAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdminAdd.setText("Add Admin");
        btnAdminAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdminAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAddActionPerformed(evt);
            }
        });

        btnAdminUpdate.setBackground(new java.awt.Color(184, 219, 217));
        btnAdminUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdminUpdate.setText("Update Admin");
        btnAdminUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUpdateActionPerformed(evt);
            }
        });

        btnAdminDelete.setBackground(new java.awt.Color(184, 219, 217));
        btnAdminDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdminDelete.setText("Delete Admin");
        btnAdminDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdminDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDeleteActionPerformed(evt);
            }
        });

        btnClearAdmin.setBackground(new java.awt.Color(184, 219, 217));
        btnClearAdmin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClearAdmin.setText("Clear Form");
        btnClearAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClearAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSupplierCode1)
                                    .addComponent(lblAdminCode))
                                .addGap(12, 12, 12)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdminCode, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdminPhone)
                                    .addComponent(lblAdminUsername)
                                    .addComponent(lblAdminPass)
                                    .addComponent(lblAdminEmail))
                                .addGap(12, 12, 12)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addComponent(btnClearAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnAdminAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminCode)
                    .addComponent(txtAdminCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierCode1)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPass))
                .addGap(9, 9, 9)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminEmail))
                .addGap(6, 6, 6)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdmin);

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                        .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        Item item = new Item();
        this.dispose();
        item.setVisible(true);

    }//GEN-LAST:event_btnItemActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        Category category = new Category();
        this.dispose();
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        Supplier supplier = new Supplier();
        this.dispose();
        supplier.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        Admin admin = new Admin();
        this.dispose();
        admin.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Yakin akan logout?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        HalamanLogin halLogin = new HalamanLogin();
        this.dispose();
        halLogin.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        HalamanUtama halUtama = new HalamanUtama();
        this.dispose();
        halUtama.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtAdminCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminCodeActionPerformed

    }//GEN-LAST:event_txtAdminCodeActionPerformed

    private void txtAdminCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminCodeKeyTyped

    }//GEN-LAST:event_txtAdminCodeKeyTyped

    private void btnAdminAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAddActionPerformed
        String adminName = txtAdminName.getText();
        String adminUsername = txtAdminUsername.getText();
        String adminPassword = txtAdminPassword.getText();
        String adminEmail = txtAdminEmail.getText();
        String adminPhone = txtAdminPhone.getText();

        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "INSERT INTO admin (admin_name,username,password,admin_email,admin_phone) VALUES ('"+adminName+"',"
            + "'"+adminUsername+"',"
            + "'"+adminPassword+"',"
            + "'"+adminEmail+"',"
            + "'"+adminPhone+"')";
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            loadAdminTable();
            clearAdmin();
        }
    }//GEN-LAST:event_btnAdminAddActionPerformed

    private void btnAdminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUpdateActionPerformed
        String adminCode = txtAdminCode.getText();
        String adminName = txtAdminName.getText();
        String adminUsername = txtAdminUsername.getText();
        String adminPassword = txtAdminPassword.getText();
        String adminEmail = txtAdminEmail.getText();
        String adminPhone = txtAdminPhone.getText();
        
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "UPDATE admin "
                    + "SET admin_name='"+adminName+"',"
                    + "username='"+adminUsername+"',"
                    + "password='"+adminPassword+"',"
                    + "admin_email='"+adminEmail+"',"
                    + "admin_phone='"+adminPhone+"' "
                    + "WHERE admin_code='"+adminCode+"';";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }  finally {
            loadAdminTable();
            clearAdmin();
        }
    }//GEN-LAST:event_btnAdminUpdateActionPerformed

    private void btnAdminDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDeleteActionPerformed
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql ="delete from admin where admin_code='"+txtAdminCode.getText()+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
            con.close();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally {
            loadAdminTable();
            clearAdmin();
        }
    }//GEN-LAST:event_btnAdminDeleteActionPerformed

    private void btnClearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAdminActionPerformed
        clearAdmin();
    }//GEN-LAST:event_btnClearAdminActionPerformed

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        int row = tblAdmin.rowAtPoint(evt.getPoint());
        String adminCode = tblAdmin.getValueAt(row, 1).toString();
        String adminName =tblAdmin.getValueAt(row, 2).toString();
        String adminUsername =tblAdmin.getValueAt(row, 3).toString();
        String adminPassword =tblAdmin.getValueAt(row, 4).toString();
        String adminEmail =tblAdmin.getValueAt(row, 5).toString();
        String adminPhone =tblAdmin.getValueAt(row, 6).toString();

        txtAdminCode.setText(adminCode);
        txtAdminName.setText(adminName);
        txtAdminUsername.setText(adminUsername);
        txtAdminPassword.setText(adminPassword);
        txtAdminEmail.setText(adminEmail);
        txtAdminPhone.setText(adminPhone);
        loadAdminTable();
    }//GEN-LAST:event_tblAdminMouseClicked

    
    //Function Load Table Admin
    private void loadAdminTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Admin Code");
        model.addColumn("Admin Name");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Admin Email");
        model.addColumn("Admin Phone");
        
        try {
            int no=1;
            sql = "SELECT * FROM admin";
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)}
                );
            }
            tblAdmin.setModel(model);
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    //Function Clear Form
    private void clearAdmin() {
        txtAdminCode.setText(null);
        txtAdminName.setText(null);
        txtAdminUsername.setText(null);
        txtAdminPassword.setText(null);
        txtAdminEmail.setText(null);
        txtAdminPhone.setText(null);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAdminAdd;
    private javax.swing.JButton btnAdminDelete;
    private javax.swing.JButton btnAdminUpdate;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnClearAdmin;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdminCode;
    private javax.swing.JLabel lblAdminEmail;
    private javax.swing.JLabel lblAdminPass;
    private javax.swing.JLabel lblAdminPhone;
    private javax.swing.JLabel lblAdminUsername;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSupplierCode1;
    private javax.swing.JLabel lblSystemImg;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlJudul;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextField txtAdminCode;
    private javax.swing.JTextField txtAdminEmail;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPassword;
    private javax.swing.JTextField txtAdminPhone;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
