/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanagementapp;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUSROG
 */
public class Item extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    /**
     * Creates new form Item
     */
    public Item() {
        initComponents();
        updateComboCategory();
        updateComboSupp();
        loadItemTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblSystemImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnItem = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlJudul = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        pnlItemForm = new javax.swing.JPanel();
        lblItemCode = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblItemCategory = new javax.swing.JLabel();
        lblItemCategoryCode = new javax.swing.JLabel();
        lblItemQty = new javax.swing.JLabel();
        lblItemSupplier = new javax.swing.JLabel();
        lblItemSupplierCode = new javax.swing.JLabel();
        txtItemCategoryCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        comboItemCategory = new javax.swing.JComboBox<>();
        txtItemCode = new javax.swing.JTextField();
        txtItemQty = new javax.swing.JTextField();
        txtItemSupplierCode = new javax.swing.JTextField();
        btnItemAdd = new javax.swing.JButton();
        btnItemUpdate = new javax.swing.JButton();
        btnItemDelete = new javax.swing.JButton();
        comboItemSupplier = new javax.swing.JComboBox<>();
        lblWarningQty = new javax.swing.JLabel();
        btnClearForm = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(88, 111, 124));

        pnlLeft.setBackground(new java.awt.Color(47, 69, 80));

        lblSystemImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-system.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 244, 249));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Management System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 249));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventory");

        btnItem.setBackground(new java.awt.Color(184, 219, 217));
        btnItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-item-32.png"))); // NOI18N
        btnItem.setText("     Item");
        btnItem.setBorder(null);
        btnItem.setFocusPainted(false);
        btnItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });

        btnCategory.setBackground(new java.awt.Color(184, 219, 217));
        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-category-32.png"))); // NOI18N
        btnCategory.setText("    Category");
        btnCategory.setBorder(null);
        btnCategory.setFocusPainted(false);
        btnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-warehouse-32.png"))); // NOI18N
        btnSupplier.setText("    Supplier");
        btnSupplier.setBorder(null);
        btnSupplier.setFocusPainted(false);
        btnSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(184, 219, 217));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-admin-32.png"))); // NOI18N
        btnAdmin.setText("   Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin.setIconTextGap(10);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        lblLogout.setForeground(new java.awt.Color(184, 219, 217));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-logout-32.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setPreferredSize(new java.awt.Dimension(30, 30));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblSystemImg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSystemImg)
                .addGap(27, 27, 27)
                .addComponent(btnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlRight.setBackground(new java.awt.Color(88, 111, 124));

        pnlJudul.setBackground(new java.awt.Color(88, 111, 124));

        lblItem.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblItem.setForeground(new java.awt.Color(244, 244, 249));
        lblItem.setText("Item");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-back-32.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlJudulLayout = new javax.swing.GroupLayout(pnlJudul);
        pnlJudul.setLayout(pnlJudulLayout);
        pnlJudulLayout.setHorizontalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlJudulLayout.setVerticalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addGroup(pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlJudulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblItem))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlItemForm.setBackground(new java.awt.Color(88, 111, 124));

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(244, 244, 249));
        lblItemCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemCode.setText("Item Code :");

        lblItemName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(244, 244, 249));
        lblItemName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemName.setText("Item Name :");

        lblItemCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemCategory.setForeground(new java.awt.Color(244, 244, 249));
        lblItemCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemCategory.setText("Item Category :");

        lblItemCategoryCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemCategoryCode.setForeground(new java.awt.Color(244, 244, 249));
        lblItemCategoryCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemCategoryCode.setText("Category Code :");

        lblItemQty.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemQty.setForeground(new java.awt.Color(244, 244, 249));
        lblItemQty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemQty.setText("Item Quantity :");

        lblItemSupplier.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemSupplier.setForeground(new java.awt.Color(244, 244, 249));
        lblItemSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemSupplier.setText("Item Supplier :");

        lblItemSupplierCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblItemSupplierCode.setForeground(new java.awt.Color(244, 244, 249));
        lblItemSupplierCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblItemSupplierCode.setText("Supplier Code :");

        txtItemCategoryCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtItemName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        comboItemCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboItemCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemCategoryMouseClicked(evt);
            }
        });
        comboItemCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemCategoryActionPerformed(evt);
            }
        });

        txtItemCode.setEditable(false);
        txtItemCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtItemCode.setEnabled(false);

        txtItemQty.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtItemQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemQtyActionPerformed(evt);
            }
        });
        txtItemQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemQtyKeyTyped(evt);
            }
        });

        txtItemSupplierCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnItemAdd.setBackground(new java.awt.Color(184, 219, 217));
        btnItemAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItemAdd.setText("Add Item");
        btnItemAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemAddActionPerformed(evt);
            }
        });

        btnItemUpdate.setBackground(new java.awt.Color(184, 219, 217));
        btnItemUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItemUpdate.setText("Update Item");
        btnItemUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemUpdateActionPerformed(evt);
            }
        });

        btnItemDelete.setBackground(new java.awt.Color(184, 219, 217));
        btnItemDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItemDelete.setText("Delete Item");
        btnItemDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDeleteActionPerformed(evt);
            }
        });

        comboItemSupplier.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboItemSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemSupplierMouseClicked(evt);
            }
        });
        comboItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemSupplierActionPerformed(evt);
            }
        });

        lblWarningQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWarningQty.setForeground(new java.awt.Color(255, 94, 91));

        btnClearForm.setBackground(new java.awt.Color(184, 219, 217));
        btnClearForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearForm.setText("Clear Form");
        btnClearForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItemFormLayout = new javax.swing.GroupLayout(pnlItemForm);
        pnlItemForm.setLayout(pnlItemFormLayout);
        pnlItemFormLayout.setHorizontalGroup(
            pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemFormLayout.createSequentialGroup()
                .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemFormLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlItemFormLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemQty, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItemName)
                            .addComponent(comboItemCategory, 0, 164, Short.MAX_VALUE)
                            .addComponent(txtItemCode)
                            .addComponent(txtItemQty)
                            .addComponent(comboItemSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarningQty, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlItemFormLayout.createSequentialGroup()
                                    .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblItemCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlItemFormLayout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(lblItemSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtItemCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlItemFormLayout.setVerticalGroup(
            pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemFormLayout.createSequentialGroup()
                .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemFormLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemCode)
                            .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemFormLayout.createSequentialGroup()
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemCategory)
                            .addComponent(comboItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemQty)
                            .addComponent(txtItemQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemSupplier)
                            .addComponent(comboItemSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemSupplierCode)
                            .addComponent(txtItemSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlItemFormLayout.createSequentialGroup()
                        .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemCategoryCode)
                            .addComponent(txtItemCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblWarningQty)))
                .addGap(42, 42, 42)
                .addGroup(pnlItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlTable.setBackground(new java.awt.Color(88, 111, 124));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pnlItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        Item item = new Item();
        this.dispose();
        item.setVisible(true);
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemUpdateActionPerformed
        String itemCode = txtItemCode.getText();
        String itemName = txtItemName.getText();
        String categoryCode = txtItemCategoryCode.getText();
        String itemCategory = (String) comboItemCategory.getSelectedItem();
        Integer itemQty = Integer.valueOf(txtItemQty.getText());
        String suppCode = txtItemSupplierCode.getText();
        String itemSupplier = (String) comboItemSupplier.getSelectedItem();
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "UPDATE item "
                    + "SET item_name='"+itemName+"',"
                    + "category_code='"+categoryCode+"',"
                    + "item_category='"+itemCategory+"',"
                    + "item_qty='"+itemQty+"',"
                    + "supplier_code='"+suppCode+"',"
                    + "item_supp='"+itemSupplier+"'"
                    + "WHERE item_code='"+itemCode+"';";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }  finally {
            loadItemTable();
            clearItem();
        }
    }//GEN-LAST:event_btnItemUpdateActionPerformed

    private void btnItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAddActionPerformed
        String itemName = txtItemName.getText();
        String categoryCode = txtItemCategoryCode.getText();
        String itemCategory = (String) comboItemCategory.getSelectedItem();
        Integer itemQty = Integer.valueOf(txtItemQty.getText());
        String suppCode = txtItemSupplierCode.getText();
        String itemSupplier = (String) comboItemSupplier.getSelectedItem();
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "INSERT INTO item (item_name, category_code, item_category, item_qty, supplier_code, item_supp) "
                    + "VALUES ('"+itemName+"','"+categoryCode+"','"+itemCategory+"','"+itemQty+"','"+suppCode+"','"+itemSupplier+"');";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
            loadItemTable();
            clearItem();
        }
        
    }//GEN-LAST:event_btnItemAddActionPerformed

    private void comboItemCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemCategoryActionPerformed
        String categoryName = (String) comboItemCategory.getSelectedItem();
        sql = "SELECT category_code FROM category WHERE category_name = '"+categoryName+"'";
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
        while (rs.next()) {
            txtItemCategoryCode.setText(rs.getString("category_code"));
        }
        con.close();
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_comboItemCategoryActionPerformed

    private void comboItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemSupplierActionPerformed
        String supplierName = (String) comboItemSupplier.getSelectedItem();
        sql = "SELECT supplier_code FROM supplier WHERE supplier_name = '"+supplierName+"'";
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
        while (rs.next()) {
            txtItemSupplierCode.setText(rs.getString("supplier_code"));
        }
        con.close();
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_comboItemSupplierActionPerformed

    private void txtItemQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemQtyActionPerformed

    private void txtItemQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemQtyKeyTyped
        String value = txtItemQty.getText();
            if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
               txtItemQty.setEditable(true);
               lblWarningQty.setText("");
            } else {
               lblWarningQty.setText("* Enter only numeric digits(0-9)");
            }
    }//GEN-LAST:event_txtItemQtyKeyTyped

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        int row = tblItem.rowAtPoint(evt.getPoint());
        String itemCode = tblItem.getValueAt(row, 1).toString();
        String itemName =tblItem.getValueAt(row, 2).toString();
        String categoryCode =tblItem.getValueAt(row, 3).toString();
        String categoryName =tblItem.getValueAt(row, 4).toString();
        String itemQty =tblItem.getValueAt(row, 5).toString();
        String suppCode =tblItem.getValueAt(row, 6).toString();
        String suppName =tblItem.getValueAt(row, 7).toString();
        
        txtItemCode.setText(itemCode);
        txtItemName.setText(itemName);
        txtItemCategoryCode.setText(categoryCode);
        comboItemCategory.setSelectedItem(categoryName);
        txtItemQty.setText(itemQty);
        txtItemSupplierCode.setText(suppCode);
        comboItemSupplier.setSelectedItem(suppName);
    }//GEN-LAST:event_tblItemMouseClicked

    private void btnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDeleteActionPerformed
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql ="delete from item where item_code='"+txtItemCode.getText()+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
            con.close();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally {
            loadItemTable();
            clearItem();
        }
        
    }//GEN-LAST:event_btnItemDeleteActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        clearItem();
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        HalamanUtama halUtama = new HalamanUtama();
        this.dispose();
        halUtama.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        Category category = new Category();
        this.dispose();
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        Supplier supplier = new Supplier();
        this.dispose();
        supplier.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
       Admin admin = new Admin();
       this.dispose();
       admin.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Yakin akan logout?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            HalamanLogin halLogin = new HalamanLogin();
            this.dispose();
            halLogin.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void comboItemCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCategoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCategoryMouseClicked

    private void comboItemSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemSupplierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemSupplierMouseClicked

    //Function ComboBox
    private void updateComboCategory() {
        try {
            sql = "SELECT * FROM category";
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                comboItemCategory.addItem(rs.getString("category_name"));
            }
            con.close();
        } catch (SQLException e) {
            System.err.println("Error: " + e);
        }
}
    private void updateComboSupp() {
        try {
            sql = "SELECT * FROM supplier";
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                comboItemSupplier.addItem(rs.getString("supplier_name"));
            }
            con.close();
        } catch (SQLException e) {
            System.err.println("Error: " + e);
        }
}
    
    //Function Tampil Data Item di Tabel
    private void loadItemTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Item Code");
        model.addColumn("Item Name");
        model.addColumn("Category Code");
        model.addColumn("Category Name");
        model.addColumn("Item Quantity");
        model.addColumn("Supplier Code");
        model.addColumn("Supplier Name");
        
        try {
            int no=1;
            sql = "SELECT * FROM item";
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)}
                );
            }
            tblItem.setModel(model);
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        updateComboCategory();
        updateComboSupp();
    }
    //Function Hapus Data pada Form
    private void clearItem() {
        txtItemCode.setText(null);
        txtItemName.setText(null);
        txtItemCategoryCode.setText(null);
        comboItemCategory.setSelectedItem(null);
        txtItemQty.setText(null);
        txtItemSupplierCode.setText(null);
        comboItemSupplier.setSelectedItem(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnItemAdd;
    private javax.swing.JButton btnItemDelete;
    private javax.swing.JButton btnItemUpdate;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JComboBox<String> comboItemCategory;
    private javax.swing.JComboBox<String> comboItemSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItemCategory;
    private javax.swing.JLabel lblItemCategoryCode;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemQty;
    private javax.swing.JLabel lblItemSupplier;
    private javax.swing.JLabel lblItemSupplierCode;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSystemImg;
    private javax.swing.JLabel lblWarningQty;
    private javax.swing.JPanel pnlItemForm;
    private javax.swing.JPanel pnlJudul;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtItemCategoryCode;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemQty;
    private javax.swing.JTextField txtItemSupplierCode;
    // End of variables declaration//GEN-END:variables
}
