/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanagementapp;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUSROG
 */
public class Supplier extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        loadSupplierTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblSystemImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnItem = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlJudul = new javax.swing.JPanel();
        lblSupplier = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        lblSupplierCode = new javax.swing.JLabel();
        txtSupplierCode = new javax.swing.JTextField();
        lblSupplierName = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        lblSupplierName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSupplierAddress = new javax.swing.JTextArea();
        lblSupplierEmail = new javax.swing.JLabel();
        txtSupplierEmail = new javax.swing.JTextField();
        lblSupplierPhone = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        btnSupplierAdd = new javax.swing.JButton();
        btnSupplierUpdate = new javax.swing.JButton();
        btnSupplierDelete = new javax.swing.JButton();
        btnClearSupplier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(88, 111, 124));

        pnlLeft.setBackground(new java.awt.Color(47, 69, 80));

        lblSystemImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-system.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 244, 249));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Management System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 249));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventory");

        btnItem.setBackground(new java.awt.Color(184, 219, 217));
        btnItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-item-32.png"))); // NOI18N
        btnItem.setText("     Item");
        btnItem.setBorder(null);
        btnItem.setFocusPainted(false);
        btnItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });

        btnCategory.setBackground(new java.awt.Color(184, 219, 217));
        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-category-32.png"))); // NOI18N
        btnCategory.setText("    Category");
        btnCategory.setBorder(null);
        btnCategory.setFocusPainted(false);
        btnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-warehouse-32.png"))); // NOI18N
        btnSupplier.setText("    Supplier");
        btnSupplier.setBorder(null);
        btnSupplier.setFocusPainted(false);
        btnSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(184, 219, 217));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-admin-32.png"))); // NOI18N
        btnAdmin.setText("   Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin.setIconTextGap(10);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        lblLogout.setForeground(new java.awt.Color(184, 219, 217));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-logout-32.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setPreferredSize(new java.awt.Dimension(30, 30));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblSystemImg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSystemImg)
                .addGap(27, 27, 27)
                .addComponent(btnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pnlRight.setBackground(new java.awt.Color(88, 111, 124));

        pnlJudul.setBackground(new java.awt.Color(88, 111, 124));

        lblSupplier.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplier.setText("Supplier");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementapp/icon-back-32.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlJudulLayout = new javax.swing.GroupLayout(pnlJudul);
        pnlJudul.setLayout(pnlJudulLayout);
        pnlJudulLayout.setHorizontalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlJudulLayout.setVerticalGroup(
            pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlJudulLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBack)))
                .addGap(44, 44, 44))
        );

        pnlForm.setBackground(new java.awt.Color(88, 111, 124));

        lblSupplierCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierCode.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierCode.setText("Supplier Code :");

        txtSupplierCode.setEditable(false);
        txtSupplierCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupplierCode.setEnabled(false);
        txtSupplierCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCodeActionPerformed(evt);
            }
        });
        txtSupplierCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSupplierCodeKeyTyped(evt);
            }
        });

        lblSupplierName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierName.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierName.setText("Supplier Name :");

        txtSupplierName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblSupplierName1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierName1.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierName1.setText("Supplier Address :");

        txtSupplierAddress.setColumns(20);
        txtSupplierAddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSupplierAddress.setRows(5);
        jScrollPane1.setViewportView(txtSupplierAddress);

        lblSupplierEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierEmail.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierEmail.setText("Supplier Email :");

        txtSupplierEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblSupplierPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSupplierPhone.setForeground(new java.awt.Color(244, 244, 249));
        lblSupplierPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplierPhone.setText("Supplier Phone :");

        txtSupplierPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnSupplierAdd.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplierAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSupplierAdd.setText("Add Supplier");
        btnSupplierAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSupplierAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierAddActionPerformed(evt);
            }
        });

        btnSupplierUpdate.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplierUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSupplierUpdate.setText("Update Supplier");
        btnSupplierUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSupplierUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierUpdateActionPerformed(evt);
            }
        });

        btnSupplierDelete.setBackground(new java.awt.Color(184, 219, 217));
        btnSupplierDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSupplierDelete.setText("Delete Supplier");
        btnSupplierDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSupplierDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDeleteActionPerformed(evt);
            }
        });

        btnClearSupplier.setBackground(new java.awt.Color(184, 219, 217));
        btnClearSupplier.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClearSupplier.setText("Clear Form");
        btnClearSupplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClearSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSupplierName)
                            .addComponent(lblSupplierCode))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(txtSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSupplierEmail)
                            .addComponent(lblSupplierName1)
                            .addComponent(lblSupplierPhone))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btnSupplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplierDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierCode)
                    .addComponent(txtSupplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierName)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierName1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierEmail))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierPhone))
                .addGap(30, 30, 30)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        Item item = new Item();
        this.dispose();
        item.setVisible(true);

    }//GEN-LAST:event_btnItemActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        Category category = new Category();
        this.dispose();
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        Supplier supplier = new Supplier();
        this.dispose();
        supplier.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        Admin admin = new Admin();
        this.dispose();
        admin.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Yakin akan logout?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        HalamanLogin halLogin = new HalamanLogin();
        this.dispose();
        halLogin.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        HalamanUtama halUtama = new HalamanUtama();
        this.dispose();
        halUtama.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtSupplierCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCodeActionPerformed

    }//GEN-LAST:event_txtSupplierCodeActionPerformed

    private void txtSupplierCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCodeKeyTyped

    }//GEN-LAST:event_txtSupplierCodeKeyTyped

    private void btnSupplierAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierAddActionPerformed
        String supplierName = txtSupplierName.getText();
        String supplierAddress = txtSupplierAddress.getText();
        String supplierEmail = txtSupplierEmail.getText();
        String supplierPhone = txtSupplierPhone.getText();
        
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "INSERT INTO supplier (supplier_name,supplier_address,supplier_email,supplier_phone) VALUES ('"+supplierName+"',"
                    + "'"+supplierAddress+"',"
                    + "'"+supplierEmail+"',"
                    + "'"+supplierPhone+"')";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
            loadSupplierTable();
            clearSupplier();
        }
    }//GEN-LAST:event_btnSupplierAddActionPerformed

    private void btnSupplierUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierUpdateActionPerformed
        String supplierCode = txtSupplierCode.getText();
        String supplierName = txtSupplierName.getText();
        String supplierAddress = txtSupplierAddress.getText();
        String supplierEmail = txtSupplierEmail.getText();
        String supplierPhone = txtSupplierPhone.getText();
        
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql = "UPDATE supplier "
                    + "SET supplier_name='"+supplierName+"',"
                    + "supplier_address='"+supplierAddress+"',"
                    + "supplier_email='"+supplierEmail+"',"
                    + "supplier_phone='"+supplierPhone+"' "
                    + "WHERE supplier_code='"+supplierCode+"';";
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }  finally {
            loadSupplierTable();
            clearSupplier();
        }
    }//GEN-LAST:event_btnSupplierUpdateActionPerformed

    private void btnSupplierDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDeleteActionPerformed
        try {
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql ="delete from supplier where supplier_code='"+txtSupplierCode.getText()+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
            con.close();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally {
            loadSupplierTable();
            clearSupplier();
        }
    }//GEN-LAST:event_btnSupplierDeleteActionPerformed

    private void btnClearSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSupplierActionPerformed
        clearSupplier();
    }//GEN-LAST:event_btnClearSupplierActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        int row = tblSupplier.rowAtPoint(evt.getPoint());
        String supplierCode = tblSupplier.getValueAt(row, 1).toString();
        String supplierName =tblSupplier.getValueAt(row, 2).toString();
        String supplierAddress =tblSupplier.getValueAt(row, 3).toString();
        String supplierEmail =tblSupplier.getValueAt(row, 4).toString();
        String supplierPhone =tblSupplier.getValueAt(row, 5).toString();
        
        txtSupplierCode.setText(supplierCode);
        txtSupplierName.setText(supplierName);
        txtSupplierAddress.setText(supplierAddress);
        txtSupplierEmail.setText(supplierEmail);
        txtSupplierPhone.setText(supplierPhone);
    }//GEN-LAST:event_tblSupplierMouseClicked

    
    //Function Load Table Supplier
    private void loadSupplierTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Supplier Code");
        model.addColumn("Supplier Name");
        model.addColumn("Supplier Address");
        model.addColumn("Supplier Email");
        model.addColumn("Supplier Phone");
        
        try {
            int no=1;
            sql = "SELECT * FROM supplier";
            Koneksi DB = new Koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)}
                );
            }
            tblSupplier.setModel(model);
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    //Function Clear Form
    private void clearSupplier() {
        txtSupplierCode.setText(null);
        txtSupplierName.setText(null);
        txtSupplierAddress.setText(null);
        txtSupplierEmail.setText(null);
        txtSupplierPhone.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnClearSupplier;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnSupplierAdd;
    private javax.swing.JButton btnSupplierDelete;
    private javax.swing.JButton btnSupplierUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblSupplierCode;
    private javax.swing.JLabel lblSupplierEmail;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblSupplierName1;
    private javax.swing.JLabel lblSupplierPhone;
    private javax.swing.JLabel lblSystemImg;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlJudul;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextArea txtSupplierAddress;
    private javax.swing.JTextField txtSupplierCode;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierPhone;
    // End of variables declaration//GEN-END:variables
}
